# Dockerfile for dashboard-service
FROM alpine:3.18

RUN apk add --no-cache curl unzip

ARG VERSION=v0.0.5
ARG ARCH=darwin_arm64
ENV PORT=9002
ENV COUNTING_SERVICE_URL=http://localhost:9003

WORKDIR /app

COPY dashboard-service .

EXPOSE ${PORT}

CMD ["./dashboard-service"]
