# Dockerfile for counting-service
FROM alpine:3.18

RUN apk add --no-cache curl unzip

ARG VERSION=v0.0.5
ARG ARCH=darwin_arm64
ENV PORT=9003

WORKDIR /app

COPY counting-service .

EXPOSE ${PORT}

CMD ["./counting-service"]
